language: python
python:
- '3.4'
- '3.5'
- 3.5-dev
- '3.6'
- 3.6-dev
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libglib2.0-0
install:
- pip install -r requirements.txt
- pip install nose coverage
- pip install coveralls
script:
- python3 setup.py nosetests --with-coverage --cover-package fer --verbosity=2
after_success:
- coveralls
deploy:
  provider: pypi
  user: jshenk
  skip_cleanup: true
  on:
    tags: true
    branch: master
  password:
    secure: HNn8kulj6svgmW3s+UQhvSxTHYEhJoGXVuEX2SxT8LP5X0RG1VoPY+g1ToVKlV3QVT8YlzrnDdbUPx0hBL/C9YpS9UWi3znoaXrQ+edbC9kf/bHDGd/UzIVjFgD948kbI3xUDIUTpyjwMswWLA1fZtjrbS4NIcQYRhF+zbl/+XIHD4sKuNXpbSMNdU1GFYo/BjQ+K5Wn7cPM4qDkTYz1p8sxVzjuqHWjh53ZWCZJgc98P1YxhN5/InB1CaJ2JUQwlEDLmxZwhD+w/5M4m0t3FbqBYm94fJ0lNCWrh5uAgembe2vO7ZvIVmEQtZt2lIZnU2QwTZzMsNJiPL5UaSZs3pF72Ag+vhXjZDhlRDfolpkD3jL2CNVk7lbV5QdU8Lmroe/XvbP+1a2sGzPLD/2uv6l2IxOzmNy9fWJ2dRF3bRvkxpZb/H5qL7sPJS87G00UfA9dTki03Wfo07yX8WdZr7z5s1oMG36mjqetJFbFe1oxsV5V7jW807x6XVyZuDZeWWcppHwrLF9z2zhx1cFt8xp87jwvlgCVUxFmKAgSMMdnETI2m2wZSRCU2egCxm14p5fWiw1kaoHpe6M/oy7nlKyenG+dfn5BXcOjuNzHxQnwxwWmnBsaTbF+UZRxXHHhy82sZoMOk+GL163cbFLe1cWa0ai/qOI/rFpjeBV5zpE=
